name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: MihirDesaiCV.tex
          compiler: xelatex

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: MihirDesaiCV.pdf
